# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.AccountStateType do
  @moduledoc """
  The state required for the account holder. > Permitted values: `Processing`, `Payout`.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.AccountStateType do
  def decode(value, _options) do
    value
  end
end

