# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountHolderStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"events",
    :"payoutState",
    :"processingState",
    :"status",
    :"statusReason"
  ]

  @type t :: %__MODULE__{
    :"events" => [Adyen.Model.AccountEvent.t] | nil,
    :"payoutState" => Adyen.Model.AccountPayoutState.t | nil,
    :"processingState" => Adyen.Model.AccountProcessingState.t | nil,
    :"status" => Adyen.Model.Status1.t,
    :"statusReason" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountHolderStatus do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"events", :list, Adyen.Model.AccountEvent, options)
    |> deserialize(:"payoutState", :struct, Adyen.Model.AccountPayoutState, options)
    |> deserialize(:"processingState", :struct, Adyen.Model.AccountProcessingState, options)
    |> deserialize(:"status", :struct, Adyen.Model.Status1, options)
  end
end

