# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountTransactionList do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"hasNextPage",
    :"transactions"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t | nil,
    :"hasNextPage" => boolean() | nil,
    :"transactions" => [Adyen.Model.Transaction.t] | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountTransactionList do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"transactions", :list, Adyen.Model.Transaction, options)
  end
end

