# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountEvent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"event",
    :"executionDate",
    :"reason"
  ]

  @type t :: %__MODULE__{
    :"event" => Adyen.Model.Event.t,
    :"executionDate" => DateTime.t,
    :"reason" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountEvent do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"event", :struct, Adyen.Model.Event, options)
  end
end

