# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountDetailBalance do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"detailBalance"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t | nil,
    :"detailBalance" => Adyen.Model.DetailBalance.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountDetailBalance do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"detailBalance", :struct, Adyen.Model.DetailBalance, options)
  end
end

