# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountProcessingState do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"disableReason",
    :"disabled",
    :"processedFrom",
    :"processedTo",
    :"tierNumber"
  ]

  @type t :: %__MODULE__{
    :"disableReason" => String.t | nil,
    :"disabled" => boolean() | nil,
    :"processedFrom" => Adyen.Model.Amount.t | nil,
    :"processedTo" => Adyen.Model.Amount.t | nil,
    :"tierNumber" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountProcessingState do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"processedFrom", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"processedTo", :struct, Adyen.Model.Amount, options)
  end
end

