# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountType do
  @moduledoc """
  Indicates the type of account. For example, for a multi-account card product. Allowed values: * notApplicable * credit * debit
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountType do
  def decode(value, _options) do
    value
  end
end

