# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountPayoutState do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"allowPayout",
    :"disableReason",
    :"disabled",
    :"notAllowedReason",
    :"payoutLimit",
    :"tierNumber"
  ]

  @type t :: %__MODULE__{
    :"allowPayout" => boolean() | nil,
    :"disableReason" => String.t | nil,
    :"disabled" => boolean() | nil,
    :"notAllowedReason" => String.t | nil,
    :"payoutLimit" => Adyen.Model.Amount.t | nil,
    :"tierNumber" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountPayoutState do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"payoutLimit", :struct, Adyen.Model.Amount, options)
  end
end

