# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.AccountPayoutState2 do
  @moduledoc """
  The payout state of the account holder.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"allowPayout",
    :"disableReason",
    :"disabled",
    :"notAllowedReason",
    :"payoutLimit",
    :"tierNumber"
  ]

  @type t :: %__MODULE__{
    :"allowPayout" => boolean() | nil,
    :"disableReason" => String.t | nil,
    :"disabled" => boolean() | nil,
    :"notAllowedReason" => String.t | nil,
    :"payoutLimit" => AdyenForPlatforms:AccountAPI.Model.Amount4.t | nil,
    :"tierNumber" => integer() | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.AccountPayoutState2 do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"payoutLimit", :struct, AdyenForPlatforms:AccountAPI.Model.Amount4, options)
  end
end

