# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountHolderNotificationRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data",
    :"environment",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"data" => Adyen.Model.AccountHolderNotificationData.t,
    :"environment" => String.t,
    :"type" => Adyen.Model.Type6.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountHolderNotificationRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :struct, Adyen.Model.AccountHolderNotificationData, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type6, options)
  end
end

