# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.AccountHolderDetails2 do
  @moduledoc """
  Details of the new account holder.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"address",
    :"bankAccountDetails",
    :"bankAggregatorDataReference",
    :"businessDetails",
    :"email",
    :"fullPhoneNumber",
    :"individualDetails",
    :"legalArrangements",
    :"merchantCategoryCode",
    :"metadata",
    :"payoutMethods",
    :"principalBusinessAddress",
    :"storeDetails",
    :"webAddress"
  ]

  @type t :: %__MODULE__{
    :"address" => AdyenForPlatforms:AccountAPI.Model.ViasAddress9.t | nil,
    :"bankAccountDetails" => [AdyenForPlatforms:AccountAPI.Model.BankAccountDetail.t] | nil,
    :"bankAggregatorDataReference" => String.t | nil,
    :"businessDetails" => AdyenForPlatforms:AccountAPI.Model.BusinessDetails3.t | nil,
    :"email" => String.t,
    :"fullPhoneNumber" => String.t,
    :"individualDetails" => AdyenForPlatforms:AccountAPI.Model.IndividualDetails3.t | nil,
    :"legalArrangements" => [AdyenForPlatforms:AccountAPI.Model.LegalArrangementDetail.t] | nil,
    :"merchantCategoryCode" => String.t | nil,
    :"metadata" => %{optional(String.t) => String.t} | nil,
    :"payoutMethods" => [AdyenForPlatforms:AccountAPI.Model.PayoutMethod.t] | nil,
    :"principalBusinessAddress" => AdyenForPlatforms:AccountAPI.Model.ViasAddress6.t | nil,
    :"storeDetails" => [AdyenForPlatforms:AccountAPI.Model.StoreDetail.t] | nil,
    :"webAddress" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.AccountHolderDetails2 do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address", :struct, AdyenForPlatforms:AccountAPI.Model.ViasAddress9, options)
    |> deserialize(:"bankAccountDetails", :list, AdyenForPlatforms:AccountAPI.Model.BankAccountDetail, options)
    |> deserialize(:"businessDetails", :struct, AdyenForPlatforms:AccountAPI.Model.BusinessDetails3, options)
    |> deserialize(:"individualDetails", :struct, AdyenForPlatforms:AccountAPI.Model.IndividualDetails3, options)
    |> deserialize(:"legalArrangements", :list, AdyenForPlatforms:AccountAPI.Model.LegalArrangementDetail, options)
    |> deserialize(:"payoutMethods", :list, AdyenForPlatforms:AccountAPI.Model.PayoutMethod, options)
    |> deserialize(:"principalBusinessAddress", :struct, AdyenForPlatforms:AccountAPI.Model.ViasAddress6, options)
    |> deserialize(:"storeDetails", :list, AdyenForPlatforms:AccountAPI.Model.StoreDetail, options)
  end
end

