# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.AccountEvent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"event",
    :"executionDate",
    :"reason"
  ]

  @type t :: %__MODULE__{
    :"event" => AdyenForPlatforms:AccountAPI.Model.Event.t,
    :"executionDate" => String.t,
    :"reason" => String.t
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.AccountEvent do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"event", :struct, AdyenForPlatforms:AccountAPI.Model.Event, options)
  end
end

