# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AccountHolderPayoutNotificationContent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"accountHolderCode",
    :"amounts",
    :"bankAccountDetail",
    :"description",
    :"estimatedArrivalDate",
    :"invalidFields",
    :"merchantReference",
    :"originalPspReference",
    :"payoutAccountCountry",
    :"payoutAccountNumber",
    :"payoutBankName",
    :"payoutBranchCode",
    :"payoutReference",
    :"payoutSpeed",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t,
    :"accountHolderCode" => String.t,
    :"amounts" => [Adyen.Model.Amount.t] | nil,
    :"bankAccountDetail" => Adyen.Model.BankAccountDetail.t | nil,
    :"description" => String.t | nil,
    :"estimatedArrivalDate" => Adyen.Model.LocalDate.t | nil,
    :"invalidFields" => [Adyen.Model.ErrorFieldType.t] | nil,
    :"merchantReference" => String.t | nil,
    :"originalPspReference" => String.t | nil,
    :"payoutAccountCountry" => String.t | nil,
    :"payoutAccountNumber" => String.t | nil,
    :"payoutBankName" => String.t | nil,
    :"payoutBranchCode" => String.t | nil,
    :"payoutReference" => integer() | nil,
    :"payoutSpeed" => Adyen.Model.PayoutSpeed.t | nil,
    :"status" => Adyen.Model.OperationStatus.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AccountHolderPayoutNotificationContent do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amounts", :list, Adyen.Model.Amount, options)
    |> deserialize(:"bankAccountDetail", :struct, Adyen.Model.BankAccountDetail, options)
    |> deserialize(:"estimatedArrivalDate", :struct, Adyen.Model.LocalDate, options)
    |> deserialize(:"invalidFields", :list, Adyen.Model.ErrorFieldType, options)
    |> deserialize(:"payoutSpeed", :struct, Adyen.Model.PayoutSpeed, options)
    |> deserialize(:"status", :struct, Adyen.Model.OperationStatus, options)
  end
end

