# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Address21 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"city",
    :"country",
    :"postalCode",
    :"stateOrProvince",
    :"street",
    :"street2"
  ]

  @type t :: %__MODULE__{
    :"city" => String.t | nil,
    :"country" => String.t | nil,
    :"postalCode" => String.t | nil,
    :"stateOrProvince" => String.t | nil,
    :"street" => String.t | nil,
    :"street2" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Address21 do
  def decode(value, _options) do
    value
  end
end

