# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.Amount1 do
  @moduledoc """
  The lower bound of the processing tier (i.e., an account holder must have processed at least this amount of money in order to be placed into this tier).
  """

  @derive [Poison.Encoder]
  defstruct [
    :"currency",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"currency" => String.t,
    :"value" => integer()
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.Amount1 do
  def decode(value, _options) do
    value
  end
end

