# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.AndroidPay do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type"
  ]

  @type t :: %__MODULE__{
    :"type" => Adyen.Model.Type27.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.AndroidPay do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"type", :struct, Adyen.Model.Type27, options)
  end
end

