# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.BalanceAccount do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderId",
    :"balances",
    :"defaultCurrencyCode",
    :"description",
    :"id",
    :"paymentInstruments",
    :"reference",
    :"status",
    :"sweepConfigurations"
  ]

  @type t :: %__MODULE__{
    :"accountHolderId" => String.t,
    :"balances" => [Adyen.Model.Balance.t] | nil,
    :"defaultCurrencyCode" => String.t | nil,
    :"description" => String.t | nil,
    :"id" => String.t,
    :"paymentInstruments" => [Adyen.Model.PaymentInstrumentReference.t] | nil,
    :"reference" => String.t | nil,
    :"status" => String.t | nil,
    :"sweepConfigurations" => %{optional(String.t) => Adyen.Model.SweepConfiguration.t} | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.BalanceAccount do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"balances", :list, Adyen.Model.Balance, options)
    |> deserialize(:"paymentInstruments", :list, Adyen.Model.PaymentInstrumentReference, options)
    |> deserialize(:"sweepConfigurations", :map, Adyen.Model.SweepConfiguration, options)
  end
end

