# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.BankAccountDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountNumber",
    :"accountType",
    :"bankAccountName",
    :"bankAccountReference",
    :"bankAccountUUID",
    :"bankBicSwift",
    :"bankCity",
    :"bankCode",
    :"bankName",
    :"branchCode",
    :"checkCode",
    :"countryCode",
    :"currencyCode",
    :"iban",
    :"ownerCity",
    :"ownerCountryCode",
    :"ownerDateOfBirth",
    :"ownerHouseNumberOrName",
    :"ownerName",
    :"ownerNationality",
    :"ownerPostalCode",
    :"ownerState",
    :"ownerStreet",
    :"primaryAccount",
    :"taxId",
    :"urlForVerification"
  ]

  @type t :: %__MODULE__{
    :"accountNumber" => String.t | nil,
    :"accountType" => String.t | nil,
    :"bankAccountName" => String.t | nil,
    :"bankAccountReference" => String.t | nil,
    :"bankAccountUUID" => String.t | nil,
    :"bankBicSwift" => String.t | nil,
    :"bankCity" => String.t | nil,
    :"bankCode" => String.t | nil,
    :"bankName" => String.t | nil,
    :"branchCode" => String.t | nil,
    :"checkCode" => String.t | nil,
    :"countryCode" => String.t | nil,
    :"currencyCode" => String.t | nil,
    :"iban" => String.t | nil,
    :"ownerCity" => String.t | nil,
    :"ownerCountryCode" => String.t | nil,
    :"ownerDateOfBirth" => String.t | nil,
    :"ownerHouseNumberOrName" => String.t | nil,
    :"ownerName" => String.t | nil,
    :"ownerNationality" => String.t | nil,
    :"ownerPostalCode" => String.t | nil,
    :"ownerState" => String.t | nil,
    :"ownerStreet" => String.t | nil,
    :"primaryAccount" => boolean() | nil,
    :"taxId" => String.t | nil,
    :"urlForVerification" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.BankAccountDetail do
  def decode(value, _options) do
    value
  end
end

