# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.BeneficiarySetupNotificationContent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"destinationAccountCode",
    :"destinationAccountHolderCode",
    :"invalidFields",
    :"merchantReference",
    :"sourceAccountCode",
    :"sourceAccountHolderCode",
    :"transferDate"
  ]

  @type t :: %__MODULE__{
    :"destinationAccountCode" => String.t,
    :"destinationAccountHolderCode" => String.t,
    :"invalidFields" => [Adyen.Model.ErrorFieldType.t] | nil,
    :"merchantReference" => String.t | nil,
    :"sourceAccountCode" => String.t,
    :"sourceAccountHolderCode" => String.t,
    :"transferDate" => DateTime.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.BeneficiarySetupNotificationContent do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"invalidFields", :list, Adyen.Model.ErrorFieldType, options)
  end
end

