# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.BusinessDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"doingBusinessAs",
    :"legalBusinessName",
    :"listedUltimateParentCompany",
    :"registrationNumber",
    :"shareholders",
    :"signatories",
    :"stockExchange",
    :"stockNumber",
    :"stockTicker",
    :"taxId"
  ]

  @type t :: %__MODULE__{
    :"doingBusinessAs" => String.t | nil,
    :"legalBusinessName" => String.t | nil,
    :"listedUltimateParentCompany" => [Adyen.Model.UltimateParentCompany.t] | nil,
    :"registrationNumber" => String.t | nil,
    :"shareholders" => [Adyen.Model.ShareholderContact.t] | nil,
    :"signatories" => [Adyen.Model.SignatoryContact.t] | nil,
    :"stockExchange" => String.t | nil,
    :"stockNumber" => String.t | nil,
    :"stockTicker" => String.t | nil,
    :"taxId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.BusinessDetails do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"listedUltimateParentCompany", :list, Adyen.Model.UltimateParentCompany, options)
    |> deserialize(:"shareholders", :list, Adyen.Model.ShareholderContact, options)
    |> deserialize(:"signatories", :list, Adyen.Model.SignatoryContact, options)
  end
end

