# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CancelOrRefundRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"merchantAccount",
    :"mpiData",
    :"originalMerchantReference",
    :"originalReference",
    :"reference",
    :"tenderReference",
    :"uniqueTerminalId"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"merchantAccount" => String.t,
    :"mpiData" => Adyen.Model.ThreeDSecureData1.t | nil,
    :"originalMerchantReference" => String.t | nil,
    :"originalReference" => String.t,
    :"reference" => String.t | nil,
    :"tenderReference" => String.t | nil,
    :"uniqueTerminalId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CancelOrRefundRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"mpiData", :struct, Adyen.Model.ThreeDSecureData1, options)
  end
end

