# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Card3 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cupsecureplus.smscode",
    :"cvc",
    :"encryptedCardNumber",
    :"encryptedExpiryMonth",
    :"encryptedExpiryYear",
    :"encryptedSecurityCode",
    :"expiryMonth",
    :"expiryYear",
    :"fundingSource",
    :"holderName",
    :"number",
    :"recurringDetailReference",
    :"shopperNotificationReference",
    :"storedPaymentMethodId",
    :"threeDS2SdkVersion",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"cupsecureplus.smscode" => String.t | nil,
    :"cvc" => String.t | nil,
    :"encryptedCardNumber" => String.t,
    :"encryptedExpiryMonth" => String.t,
    :"encryptedExpiryYear" => String.t,
    :"encryptedSecurityCode" => String.t | nil,
    :"expiryMonth" => String.t | nil,
    :"expiryYear" => String.t | nil,
    :"fundingSource" => Adyen.Model.FundingSource.t | nil,
    :"holderName" => String.t | nil,
    :"number" => String.t | nil,
    :"recurringDetailReference" => String.t | nil,
    :"shopperNotificationReference" => String.t | nil,
    :"storedPaymentMethodId" => String.t | nil,
    :"threeDS2SdkVersion" => String.t | nil,
    :"type" => Adyen.Model.Type32.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Card3 do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fundingSource", :struct, Adyen.Model.FundingSource, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type32, options)
  end
end

