# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CheckoutCancelOrderRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"merchantAccount",
    :"order"
  ]

  @type t :: %__MODULE__{
    :"merchantAccount" => String.t,
    :"order" => Adyen.Model.CheckoutOrder.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CheckoutCancelOrderRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"order", :struct, Adyen.Model.CheckoutOrder, options)
  end
end

