# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CheckoutVoucherAction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"alternativeReference",
    :"collectionInstitutionNumber",
    :"downloadUrl",
    :"entity",
    :"expiresAt",
    :"initialAmount",
    :"instructionsUrl",
    :"issuer",
    :"maskedTelephoneNumber",
    :"merchantName",
    :"merchantReference",
    :"paymentData",
    :"paymentMethodType",
    :"reference",
    :"shopperEmail",
    :"shopperName",
    :"surcharge",
    :"totalAmount",
    :"type",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"alternativeReference" => String.t | nil,
    :"collectionInstitutionNumber" => String.t | nil,
    :"downloadUrl" => String.t | nil,
    :"entity" => String.t | nil,
    :"expiresAt" => String.t | nil,
    :"initialAmount" => Adyen.Model.Amount.t | nil,
    :"instructionsUrl" => String.t | nil,
    :"issuer" => String.t | nil,
    :"maskedTelephoneNumber" => String.t | nil,
    :"merchantName" => String.t | nil,
    :"merchantReference" => String.t | nil,
    :"paymentData" => String.t | nil,
    :"paymentMethodType" => String.t | nil,
    :"reference" => String.t | nil,
    :"shopperEmail" => String.t | nil,
    :"shopperName" => String.t | nil,
    :"surcharge" => Adyen.Model.Amount.t | nil,
    :"totalAmount" => Adyen.Model.Amount.t | nil,
    :"type" => String.t,
    :"url" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CheckoutVoucherAction do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"initialAmount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"surcharge", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"totalAmount", :struct, Adyen.Model.Amount, options)
  end
end

