# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CloseStoresRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"stores"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"stores" => [String.t]
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CloseStoresRequest do
  def decode(value, _options) do
    value
  end
end

