# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.CloseAccountResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"invalidFields",
    :"pspReference",
    :"resultCode",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t | nil,
    :"invalidFields" => [AdyenForPlatforms:AccountAPI.Model.ErrorFieldType.t] | nil,
    :"pspReference" => String.t | nil,
    :"resultCode" => String.t | nil,
    :"status" => AdyenForPlatforms:AccountAPI.Model.Status2.t
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.CloseAccountResponse do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"invalidFields", :list, AdyenForPlatforms:AccountAPI.Model.ErrorFieldType, options)
    |> deserialize(:"status", :struct, AdyenForPlatforms:AccountAPI.Model.Status2, options)
  end
end

