# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CompensateNegativeBalanceNotificationContent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"records"
  ]

  @type t :: %__MODULE__{
    :"records" => [Adyen.Model.CompensateNegativeBalanceNotificationRecord.t]
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CompensateNegativeBalanceNotificationContent do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"records", :list, Adyen.Model.CompensateNegativeBalanceNotificationRecord, options)
  end
end

