# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CompensateNegativeBalanceNotificationRecord do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"amount",
    :"transferDate"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t,
    :"amount" => Adyen.Model.Amount.t,
    :"transferDate" => DateTime.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CompensateNegativeBalanceNotificationRecord do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
  end
end

