# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Configuration do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"avs",
    :"cardHolderName",
    :"installments",
    :"shopperInput"
  ]

  @type t :: %__MODULE__{
    :"avs" => Adyen.Model.Avs.t | nil,
    :"cardHolderName" => Adyen.Model.CardHolderName.t | nil,
    :"installments" => Adyen.Model.InstallmentsNumber.t | nil,
    :"shopperInput" => Adyen.Model.ShopperInput.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Configuration do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avs", :struct, Adyen.Model.Avs, options)
    |> deserialize(:"cardHolderName", :struct, Adyen.Model.CardHolderName, options)
    |> deserialize(:"installments", :struct, Adyen.Model.InstallmentsNumber, options)
    |> deserialize(:"shopperInput", :struct, Adyen.Model.ShopperInput, options)
  end
end

