# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CostEstimateAssumptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"assume3DSecureAuthenticated",
    :"assumeLevel3Data",
    :"installments"
  ]

  @type t :: %__MODULE__{
    :"assume3DSecureAuthenticated" => boolean() | nil,
    :"assumeLevel3Data" => boolean() | nil,
    :"installments" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CostEstimateAssumptions do
  def decode(value, _options) do
    value
  end
end

