# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CostEstimateResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cardBin",
    :"costEstimateAmount",
    :"resultCode",
    :"surchargeType"
  ]

  @type t :: %__MODULE__{
    :"cardBin" => Adyen.Model.CardBin.t | nil,
    :"costEstimateAmount" => Adyen.Model.Amount.t | nil,
    :"resultCode" => String.t | nil,
    :"surchargeType" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CostEstimateResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"cardBin", :struct, Adyen.Model.CardBin, options)
    |> deserialize(:"costEstimateAmount", :struct, Adyen.Model.Amount, options)
  end
end

