# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CreateStandalonePaymentCancelRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"merchantAccount",
    :"paymentReference",
    :"reference"
  ]

  @type t :: %__MODULE__{
    :"merchantAccount" => String.t,
    :"paymentReference" => String.t,
    :"reference" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CreateStandalonePaymentCancelRequest do
  def decode(value, _options) do
    value
  end
end

