# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CreateAccountRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"bankAccountUUID",
    :"description",
    :"metadata",
    :"payoutMethodCode",
    :"payoutSchedule",
    :"payoutScheduleReason",
    :"payoutSpeed"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"bankAccountUUID" => String.t | nil,
    :"description" => String.t | nil,
    :"metadata" => %{optional(String.t) => String.t} | nil,
    :"payoutMethodCode" => String.t | nil,
    :"payoutSchedule" => Adyen.Model.PayoutSchedule.t | nil,
    :"payoutScheduleReason" => String.t | nil,
    :"payoutSpeed" => Adyen.Model.PayoutSpeed.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CreateAccountRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"payoutSchedule", :struct, Adyen.Model.PayoutSchedule, options)
    |> deserialize(:"payoutSpeed", :struct, Adyen.Model.PayoutSpeed, options)
  end
end

