# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CreatePaymentAmountUpdateRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"merchantAccount",
    :"reason",
    :"reference",
    :"splits"
  ]

  @type t :: %__MODULE__{
    :"amount" => Adyen.Model.Amount.t,
    :"merchantAccount" => String.t,
    :"reason" => Adyen.Model.Reason.t | nil,
    :"reference" => String.t | nil,
    :"splits" => [Adyen.Model.Split.t] | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CreatePaymentAmountUpdateRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"reason", :struct, Adyen.Model.Reason, options)
    |> deserialize(:"splits", :list, Adyen.Model.Split, options)
  end
end

