# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.CreateTestCardRangesRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"accountTypeCode",
    :"testCardRanges"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t,
    :"accountTypeCode" => String.t,
    :"testCardRanges" => [Adyen.Model.TestCardRange.t]
  }
end

defimpl Poison.Decoder, for: Adyen.Model.CreateTestCardRangesRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"testCardRanges", :list, Adyen.Model.TestCardRange, options)
  end
end

