# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.CreateAccountHolderResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"accountHolderCode",
    :"accountHolderDetails",
    :"accountHolderStatus",
    :"description",
    :"invalidFields",
    :"legalEntity",
    :"primaryCurrency",
    :"pspReference",
    :"resultCode",
    :"verification",
    :"verificationProfile"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t | nil,
    :"accountHolderCode" => String.t,
    :"accountHolderDetails" => AdyenForPlatforms:AccountAPI.Model.AccountHolderDetails2.t,
    :"accountHolderStatus" => AdyenForPlatforms:AccountAPI.Model.AccountHolderStatus2.t,
    :"description" => String.t | nil,
    :"invalidFields" => [AdyenForPlatforms:AccountAPI.Model.ErrorFieldType.t] | nil,
    :"legalEntity" => AdyenForPlatforms:AccountAPI.Model.LegalEntity1.t,
    :"primaryCurrency" => String.t | nil,
    :"pspReference" => String.t | nil,
    :"resultCode" => String.t | nil,
    :"verification" => AdyenForPlatforms:AccountAPI.Model.KycVerificationResult21.t,
    :"verificationProfile" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.CreateAccountHolderResponse do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accountHolderDetails", :struct, AdyenForPlatforms:AccountAPI.Model.AccountHolderDetails2, options)
    |> deserialize(:"accountHolderStatus", :struct, AdyenForPlatforms:AccountAPI.Model.AccountHolderStatus2, options)
    |> deserialize(:"invalidFields", :list, AdyenForPlatforms:AccountAPI.Model.ErrorFieldType, options)
    |> deserialize(:"legalEntity", :struct, AdyenForPlatforms:AccountAPI.Model.LegalEntity1, options)
    |> deserialize(:"verification", :struct, AdyenForPlatforms:AccountAPI.Model.KycVerificationResult21, options)
  end
end

