# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.DebitAccountHolderRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"amount",
    :"bankAccountUUID",
    :"description",
    :"merchantAccount",
    :"splits"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"amount" => Adyen.Model.Amount.t,
    :"bankAccountUUID" => String.t,
    :"description" => String.t | nil,
    :"merchantAccount" => String.t,
    :"splits" => [Adyen.Model.Split.t]
  }
end

defimpl Poison.Decoder, for: Adyen.Model.DebitAccountHolderRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"splits", :list, Adyen.Model.Split, options)
  end
end

