# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.DeviceRenderOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"sdkInterface",
    :"sdkUiType"
  ]

  @type t :: %__MODULE__{
    :"sdkInterface" => Adyen.Model.SdkInterface.t | nil,
    :"sdkUiType" => [Adyen.Model.SdkUiType.t] | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.DeviceRenderOptions do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"sdkInterface", :struct, Adyen.Model.SdkInterface, options)
    |> deserialize(:"sdkUiType", :list, Adyen.Model.SdkUiType, options)
  end
end

