# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.DocumentDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"bankAccountUUID",
    :"description",
    :"documentType",
    :"filename",
    :"legalArrangementCode",
    :"legalArrangementEntityCode",
    :"shareholderCode",
    :"signatoryCode"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"bankAccountUUID" => String.t | nil,
    :"description" => String.t | nil,
    :"documentType" => Adyen.Model.DocumentType.t,
    :"filename" => String.t,
    :"legalArrangementCode" => String.t | nil,
    :"legalArrangementEntityCode" => String.t | nil,
    :"shareholderCode" => String.t | nil,
    :"signatoryCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.DocumentDetail do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"documentType", :struct, Adyen.Model.DocumentType, options)
  end
end

