# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.ErrorFieldType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errorCode",
    :"errorDescription",
    :"fieldType"
  ]

  @type t :: %__MODULE__{
    :"errorCode" => integer() | nil,
    :"errorDescription" => String.t | nil,
    :"fieldType" => AdyenForPlatforms:AccountAPI.Model.FieldType2.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.ErrorFieldType do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fieldType", :struct, AdyenForPlatforms:AccountAPI.Model.FieldType2, options)
  end
end

