# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.FundSource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"billingAddress",
    :"card",
    :"shopperEmail",
    :"shopperName",
    :"telephoneNumber"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"billingAddress" => Adyen.Model.Address1.t | nil,
    :"card" => Adyen.Model.Card2.t | nil,
    :"shopperEmail" => String.t | nil,
    :"shopperName" => Adyen.Model.Name2.t | nil,
    :"telephoneNumber" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.FundSource do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"billingAddress", :struct, Adyen.Model.Address1, options)
    |> deserialize(:"card", :struct, Adyen.Model.Card2, options)
    |> deserialize(:"shopperName", :struct, Adyen.Model.Name2, options)
  end
end

