# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.GetTaxFormRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"formType",
    :"year"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"formType" => String.t,
    :"year" => integer()
  }
end

defimpl Poison.Decoder, for: Adyen.Model.GetTaxFormRequest do
  def decode(value, _options) do
    value
  end
end

