# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.GetNotificationConfigurationListResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"configurations",
    :"invalidFields",
    :"pspReference",
    :"resultCode"
  ]

  @type t :: %__MODULE__{
    :"configurations" => [Adyen.Model.NotificationConfigurationDetails.t],
    :"invalidFields" => [Adyen.Model.ErrorFieldType.t] | nil,
    :"pspReference" => String.t | nil,
    :"resultCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.GetNotificationConfigurationListResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"configurations", :list, Adyen.Model.NotificationConfigurationDetails, options)
    |> deserialize(:"invalidFields", :list, Adyen.Model.ErrorFieldType, options)
  end
end

