# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.GetNotificationConfigurationRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"notificationId"
  ]

  @type t :: %__MODULE__{
    :"notificationId" => integer()
  }
end

defimpl Poison.Decoder, for: Adyen.Model.GetNotificationConfigurationRequest do
  def decode(value, _options) do
    value
  end
end

