# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.GetAccountHolderStatusResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"accountHolderStatus",
    :"invalidFields",
    :"pspReference",
    :"resultCode"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"accountHolderStatus" => Adyen.Model.AccountHolderStatus.t,
    :"invalidFields" => [Adyen.Model.ErrorFieldType.t] | nil,
    :"pspReference" => String.t | nil,
    :"resultCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.GetAccountHolderStatusResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accountHolderStatus", :struct, Adyen.Model.AccountHolderStatus, options)
    |> deserialize(:"invalidFields", :list, Adyen.Model.ErrorFieldType, options)
  end
end

