# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.GetUploadedDocumentsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"bankAccountUUID",
    :"shareholderCode"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"bankAccountUUID" => String.t | nil,
    :"shareholderCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.GetUploadedDocumentsRequest do
  def decode(value, _options) do
    value
  end
end

