# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.GetOnboardingUrlRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"collectInformation",
    :"editMode",
    :"platformName",
    :"returnUrl",
    :"shopperLocale",
    :"showPages"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"collectInformation" => Adyen.Model.CollectInformation.t | nil,
    :"editMode" => boolean() | nil,
    :"platformName" => String.t | nil,
    :"returnUrl" => String.t | nil,
    :"shopperLocale" => String.t | nil,
    :"showPages" => Adyen.Model.ShowPages.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.GetOnboardingUrlRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"collectInformation", :struct, Adyen.Model.CollectInformation, options)
    |> deserialize(:"showPages", :struct, Adyen.Model.ShowPages, options)
  end
end

