# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Individual do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"birthData",
    :"email",
    :"identificationData",
    :"name",
    :"nationality",
    :"phone",
    :"residentialAddress",
    :"webData"
  ]

  @type t :: %__MODULE__{
    :"birthData" => Adyen.Model.BirthData.t | nil,
    :"email" => String.t | nil,
    :"identificationData" => Adyen.Model.IdentificationData.t | nil,
    :"name" => Adyen.Model.Name21.t | nil,
    :"nationality" => String.t | nil,
    :"phone" => Adyen.Model.PhoneNumber21.t | nil,
    :"residentialAddress" => Adyen.Model.Address21.t | nil,
    :"webData" => Adyen.Model.WebData.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Individual do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"birthData", :struct, Adyen.Model.BirthData, options)
    |> deserialize(:"identificationData", :struct, Adyen.Model.IdentificationData, options)
    |> deserialize(:"name", :struct, Adyen.Model.Name21, options)
    |> deserialize(:"phone", :struct, Adyen.Model.PhoneNumber21, options)
    |> deserialize(:"residentialAddress", :struct, Adyen.Model.Address21, options)
    |> deserialize(:"webData", :struct, Adyen.Model.WebData, options)
  end
end

