# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.IndividualDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"personalData"
  ]

  @type t :: %__MODULE__{
    :"name" => Adyen.Model.ViasName.t | nil,
    :"personalData" => Adyen.Model.ViasPersonalData.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.IndividualDetails do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"name", :struct, Adyen.Model.ViasName, options)
    |> deserialize(:"personalData", :struct, Adyen.Model.ViasPersonalData, options)
  end
end

