# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.InputDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"configuration",
    :"details",
    :"inputDetails",
    :"itemSearchUrl",
    :"items",
    :"key",
    :"optional",
    :"type",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"configuration" => %{optional(String.t) => String.t} | nil,
    :"details" => [Adyen.Model.SubInputDetail.t] | nil,
    :"inputDetails" => [Adyen.Model.SubInputDetail.t] | nil,
    :"itemSearchUrl" => String.t | nil,
    :"items" => [Adyen.Model.Item.t] | nil,
    :"key" => String.t | nil,
    :"optional" => boolean() | nil,
    :"type" => String.t | nil,
    :"value" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.InputDetail do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"details", :list, Adyen.Model.SubInputDetail, options)
    |> deserialize(:"inputDetails", :list, Adyen.Model.SubInputDetail, options)
    |> deserialize(:"items", :list, Adyen.Model.Item, options)
  end
end

