# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.InstallmentOption do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"maxValue",
    :"plans",
    :"preselectedValue",
    :"values"
  ]

  @type t :: %__MODULE__{
    :"maxValue" => integer() | nil,
    :"plans" => [Adyen.Model.Plan1.t] | nil,
    :"preselectedValue" => integer() | nil,
    :"values" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.InstallmentOption do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"plans", :list, Adyen.Model.Plan1, options)
  end
end

