# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Installments do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"plan",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"plan" => Adyen.Model.Plan.t | nil,
    :"value" => integer()
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Installments do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"plan", :struct, Adyen.Model.Plan, options)
  end
end

