# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.InvalidField do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"message",
    :"name",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"message" => String.t,
    :"name" => String.t,
    :"value" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.InvalidField do
  def decode(value, _options) do
    value
  end
end

