# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.KycVerificationResult2 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolder",
    :"legalArrangements",
    :"legalArrangementsEntities",
    :"payoutMethods",
    :"shareholders",
    :"signatories",
    :"ultimateParentCompany"
  ]

  @type t :: %__MODULE__{
    :"accountHolder" => Adyen.Model.KycCheckResult2.t | nil,
    :"legalArrangements" => [Adyen.Model.KycLegalArrangementCheckResult.t] | nil,
    :"legalArrangementsEntities" => [Adyen.Model.KycLegalArrangementEntityCheckResult.t] | nil,
    :"payoutMethods" => [Adyen.Model.KycPayoutMethodCheckResult.t] | nil,
    :"shareholders" => [Adyen.Model.KycShareholderCheckResult.t] | nil,
    :"signatories" => [Adyen.Model.KycSignatoryCheckResult.t] | nil,
    :"ultimateParentCompany" => [Adyen.Model.KycUltimateParentCompanyCheckResult.t] | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.KycVerificationResult2 do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accountHolder", :struct, Adyen.Model.KycCheckResult2, options)
    |> deserialize(:"legalArrangements", :list, Adyen.Model.KycLegalArrangementCheckResult, options)
    |> deserialize(:"legalArrangementsEntities", :list, Adyen.Model.KycLegalArrangementEntityCheckResult, options)
    |> deserialize(:"payoutMethods", :list, Adyen.Model.KycPayoutMethodCheckResult, options)
    |> deserialize(:"shareholders", :list, Adyen.Model.KycShareholderCheckResult, options)
    |> deserialize(:"signatories", :list, Adyen.Model.KycSignatoryCheckResult, options)
    |> deserialize(:"ultimateParentCompany", :list, Adyen.Model.KycUltimateParentCompanyCheckResult, options)
  end
end

