# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.KycCheckStatusData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"requiredFields",
    :"status",
    :"summary",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"requiredFields" => [String.t] | nil,
    :"status" => Adyen.Model.Status3.t,
    :"summary" => Adyen.Model.KycCheckSummary.t | nil,
    :"type" => Adyen.Model.Type2.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.KycCheckStatusData do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"status", :struct, Adyen.Model.Status3, options)
    |> deserialize(:"summary", :struct, Adyen.Model.KycCheckSummary, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type2, options)
  end
end

