# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.LegalEntityInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"entityAssociations",
    :"individual",
    :"organization",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"entityAssociations" => [Adyen.Model.LegalEntityAssociation.t] | nil,
    :"individual" => Adyen.Model.Individual.t | nil,
    :"organization" => Adyen.Model.Organization.t | nil,
    :"type" => Adyen.Model.Type18.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.LegalEntityInfo do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"entityAssociations", :list, Adyen.Model.LegalEntityAssociation, options)
    |> deserialize(:"individual", :struct, Adyen.Model.Individual, options)
    |> deserialize(:"organization", :struct, Adyen.Model.Organization, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type18, options)
  end
end

