# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.LegalArrangementDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"address",
    :"legalArrangementCode",
    :"legalArrangementEntities",
    :"legalArrangementReference",
    :"legalForm",
    :"name",
    :"registrationNumber",
    :"taxNumber",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"address" => AdyenForPlatforms:AccountAPI.Model.ViasAddress4.t,
    :"legalArrangementCode" => String.t | nil,
    :"legalArrangementEntities" => [AdyenForPlatforms:AccountAPI.Model.LegalArrangementEntityDetail.t] | nil,
    :"legalArrangementReference" => String.t | nil,
    :"legalForm" => AdyenForPlatforms:AccountAPI.Model.LegalForm.t | nil,
    :"name" => String.t,
    :"registrationNumber" => String.t | nil,
    :"taxNumber" => String.t | nil,
    :"type" => AdyenForPlatforms:AccountAPI.Model.Type1.t
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.LegalArrangementDetail do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address", :struct, AdyenForPlatforms:AccountAPI.Model.ViasAddress4, options)
    |> deserialize(:"legalArrangementEntities", :list, AdyenForPlatforms:AccountAPI.Model.LegalArrangementEntityDetail, options)
    |> deserialize(:"legalForm", :struct, AdyenForPlatforms:AccountAPI.Model.LegalForm, options)
    |> deserialize(:"type", :struct, AdyenForPlatforms:AccountAPI.Model.Type1, options)
  end
end

