# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.LegalArrangementEntityDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"address",
    :"businessDetails",
    :"email",
    :"fullPhoneNumber",
    :"individualDetails",
    :"legalArrangementEntityCode",
    :"legalArrangementEntityReference",
    :"legalArrangementMembers",
    :"legalEntityType",
    :"phoneNumber",
    :"webAddress"
  ]

  @type t :: %__MODULE__{
    :"address" => AdyenForPlatforms:AccountAPI.Model.ViasAddress5.t | nil,
    :"businessDetails" => AdyenForPlatforms:AccountAPI.Model.BusinessDetails1.t | nil,
    :"email" => String.t | nil,
    :"fullPhoneNumber" => String.t | nil,
    :"individualDetails" => AdyenForPlatforms:AccountAPI.Model.IndividualDetails1.t | nil,
    :"legalArrangementEntityCode" => String.t | nil,
    :"legalArrangementEntityReference" => String.t | nil,
    :"legalArrangementMembers" => [AdyenForPlatforms:AccountAPI.Model.LegalArrangementMember.t] | nil,
    :"legalEntityType" => AdyenForPlatforms:AccountAPI.Model.LegalEntityType.t,
    :"phoneNumber" => AdyenForPlatforms:AccountAPI.Model.ViasPhoneNumber2.t | nil,
    :"webAddress" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.LegalArrangementEntityDetail do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address", :struct, AdyenForPlatforms:AccountAPI.Model.ViasAddress5, options)
    |> deserialize(:"businessDetails", :struct, AdyenForPlatforms:AccountAPI.Model.BusinessDetails1, options)
    |> deserialize(:"individualDetails", :struct, AdyenForPlatforms:AccountAPI.Model.IndividualDetails1, options)
    |> deserialize(:"legalArrangementMembers", :list, AdyenForPlatforms:AccountAPI.Model.LegalArrangementMember, options)
    |> deserialize(:"legalEntityType", :struct, AdyenForPlatforms:AccountAPI.Model.LegalEntityType, options)
    |> deserialize(:"phoneNumber", :struct, AdyenForPlatforms:AccountAPI.Model.ViasPhoneNumber2, options)
  end
end

