# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.LianlianPay do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"telephoneNumber",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"telephoneNumber" => String.t,
    :"type" => Adyen.Model.Type44.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.LianlianPay do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"type", :struct, Adyen.Model.Type44, options)
  end
end

