# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.LocalDate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"month",
    :"year"
  ]

  @type t :: %__MODULE__{
    :"month" => integer() | nil,
    :"year" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.LocalDate do
  def decode(value, _options) do
    value
  end
end

