# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Mandate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"amountRule",
    :"billingAttemptsRule",
    :"billingDay",
    :"endsAt",
    :"frequency",
    :"remarks",
    :"startsAt"
  ]

  @type t :: %__MODULE__{
    :"amount" => String.t,
    :"amountRule" => Adyen.Model.AmountRule.t | nil,
    :"billingAttemptsRule" => Adyen.Model.BillingAttemptsRule.t | nil,
    :"billingDay" => String.t | nil,
    :"endsAt" => String.t,
    :"frequency" => Adyen.Model.Frequency.t,
    :"remarks" => String.t | nil,
    :"startsAt" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Mandate do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amountRule", :struct, Adyen.Model.AmountRule, options)
    |> deserialize(:"billingAttemptsRule", :struct, Adyen.Model.BillingAttemptsRule, options)
    |> deserialize(:"frequency", :struct, Adyen.Model.Frequency, options)
  end
end

