# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Masterpass do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"fundingSource",
    :"masterpassTransactionId",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"fundingSource" => Adyen.Model.FundingSource.t | nil,
    :"masterpassTransactionId" => String.t,
    :"type" => Adyen.Model.Type45.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Masterpass do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fundingSource", :struct, Adyen.Model.FundingSource, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type45, options)
  end
end

