# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.MerchantRiskIndicator do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"addressMatch",
    :"deliveryAddressIndicator",
    :"deliveryEmail",
    :"deliveryTimeframe",
    :"giftCardAmount",
    :"giftCardCount",
    :"preOrderDate",
    :"preOrderPurchase",
    :"reorderItems"
  ]

  @type t :: %__MODULE__{
    :"addressMatch" => boolean() | nil,
    :"deliveryAddressIndicator" => Adyen.Model.DeliveryAddressIndicator.t | nil,
    :"deliveryEmail" => String.t | nil,
    :"deliveryTimeframe" => Adyen.Model.DeliveryTimeframe.t | nil,
    :"giftCardAmount" => Adyen.Model.Amount.t | nil,
    :"giftCardCount" => integer() | nil,
    :"preOrderDate" => DateTime.t | nil,
    :"preOrderPurchase" => boolean() | nil,
    :"reorderItems" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.MerchantRiskIndicator do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"deliveryAddressIndicator", :struct, Adyen.Model.DeliveryAddressIndicator, options)
    |> deserialize(:"deliveryTimeframe", :struct, Adyen.Model.DeliveryTimeframe, options)
    |> deserialize(:"giftCardAmount", :struct, Adyen.Model.Amount, options)
  end
end

