# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.ModifyRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"merchantAccount",
    :"originalReference"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"merchantAccount" => String.t,
    :"originalReference" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.ModifyRequest do
  def decode(value, _options) do
    value
  end
end

