# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.NotificationConfigurationDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"active",
    :"apiVersion",
    :"description",
    :"eventConfigs",
    :"hmacSignatureKey",
    :"notificationId",
    :"notifyPassword",
    :"notifyURL",
    :"notifyUsername",
    :"sslProtocol"
  ]

  @type t :: %__MODULE__{
    :"active" => boolean() | nil,
    :"apiVersion" => integer() | nil,
    :"description" => String.t | nil,
    :"eventConfigs" => [Adyen.Model.NotificationEventConfiguration.t],
    :"hmacSignatureKey" => String.t | nil,
    :"notificationId" => integer() | nil,
    :"notifyPassword" => String.t | nil,
    :"notifyURL" => String.t,
    :"notifyUsername" => String.t | nil,
    :"sslProtocol" => Adyen.Model.SslProtocol.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.NotificationConfigurationDetails do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"eventConfigs", :list, Adyen.Model.NotificationEventConfiguration, options)
    |> deserialize(:"sslProtocol", :struct, Adyen.Model.SslProtocol, options)
  end
end

