# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PaginatedPaymentInstrumentsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hasNext",
    :"hasPrevious",
    :"paymentInstruments"
  ]

  @type t :: %__MODULE__{
    :"hasNext" => boolean(),
    :"hasPrevious" => boolean(),
    :"paymentInstruments" => [Adyen.Model.PaymentInstrument.t]
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PaginatedPaymentInstrumentsResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"paymentInstruments", :list, Adyen.Model.PaymentInstrument, options)
  end
end

