# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PayPal do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"orderID",
    :"payerID",
    :"recurringDetailReference",
    :"storedPaymentMethodId",
    :"subtype",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"orderID" => String.t | nil,
    :"payerID" => String.t | nil,
    :"recurringDetailReference" => String.t | nil,
    :"storedPaymentMethodId" => String.t | nil,
    :"subtype" => Adyen.Model.Subtype.t | nil,
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PayPal do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"subtype", :struct, Adyen.Model.Subtype, options)
  end
end

