# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PaymentSetupResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paymentSession",
    :"recurringDetails"
  ]

  @type t :: %__MODULE__{
    :"paymentSession" => String.t | nil,
    :"recurringDetails" => [Adyen.Model.RecurringDetail1.t] | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PaymentSetupResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"recurringDetails", :list, Adyen.Model.RecurringDetail1, options)
  end
end

