# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PaymentNotificationRequest2 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data",
    :"environment",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"data" => Adyen.Model.PaymentNotificationData.t,
    :"environment" => String.t,
    :"type" => Adyen.Model.Type13.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PaymentNotificationRequest2 do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :struct, Adyen.Model.PaymentNotificationData, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type13, options)
  end
end

