# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PaymentInstrumentGroup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"balancePlatform",
    :"description",
    :"id",
    :"properties",
    :"reference",
    :"txVariant"
  ]

  @type t :: %__MODULE__{
    :"balancePlatform" => String.t,
    :"description" => String.t | nil,
    :"id" => String.t | nil,
    :"properties" => %{optional(String.t) => String.t} | nil,
    :"reference" => String.t | nil,
    :"txVariant" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PaymentInstrumentGroup do
  def decode(value, _options) do
    value
  end
end

