# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PaymentResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"action",
    :"additionalData",
    :"amount",
    :"donationToken",
    :"fraudResult",
    :"merchantReference",
    :"order",
    :"pspReference",
    :"refusalReason",
    :"refusalReasonCode",
    :"resultCode",
    :"threeDS2ResponseData",
    :"threeDS2Result",
    :"threeDSPaymentData"
  ]

  @type t :: %__MODULE__{
    :"action" => OneOfCheckoutAwaitActionCheckoutBankTransferActionCheckoutDonationActionCheckoutOneTimePasscodeActionCheckoutQrCodeActionCheckoutRedirectActionCheckoutSdkActionCheckoutThreeDs2ActionCheckoutVoucherAction | nil,
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"amount" => Adyen.Model.Amount.t | nil,
    :"donationToken" => String.t | nil,
    :"fraudResult" => Adyen.Model.FraudResult.t | nil,
    :"merchantReference" => String.t | nil,
    :"order" => Adyen.Model.CheckoutOrderResponse.t | nil,
    :"pspReference" => String.t | nil,
    :"refusalReason" => String.t | nil,
    :"refusalReasonCode" => String.t | nil,
    :"resultCode" => Adyen.Model.ResultCode1.t | nil,
    :"threeDS2ResponseData" => Adyen.Model.ThreeDs2ResponseData.t | nil,
    :"threeDS2Result" => Adyen.Model.ThreeDs2Result.t | nil,
    :"threeDSPaymentData" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PaymentResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"action", :struct, Adyen.Model.OneOfCheckoutAwaitActionCheckoutBankTransferActionCheckoutDonationActionCheckoutOneTimePasscodeActionCheckoutQrCodeActionCheckoutRedirectActionCheckoutSdkActionCheckoutThreeDs2ActionCheckoutVoucherAction, options)
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"fraudResult", :struct, Adyen.Model.FraudResult, options)
    |> deserialize(:"order", :struct, Adyen.Model.CheckoutOrderResponse, options)
    |> deserialize(:"resultCode", :struct, Adyen.Model.ResultCode1, options)
    |> deserialize(:"threeDS2ResponseData", :struct, Adyen.Model.ThreeDs2ResponseData, options)
    |> deserialize(:"threeDS2Result", :struct, Adyen.Model.ThreeDs2Result, options)
  end
end

