# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PaymentLinkResource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"allowedPaymentMethods",
    :"amount",
    :"applicationInfo",
    :"billingAddress",
    :"blockedPaymentMethods",
    :"countryCode",
    :"deliverAt",
    :"deliveryAddress",
    :"description",
    :"expiresAt",
    :"id",
    :"lineItems",
    :"merchantAccount",
    :"merchantOrderReference",
    :"recurringProcessingModel",
    :"reference",
    :"returnUrl",
    :"reusable",
    :"riskData",
    :"shopperEmail",
    :"shopperLocale",
    :"shopperName",
    :"shopperReference",
    :"splits",
    :"status",
    :"store",
    :"storePaymentMethod",
    :"url"
  ]

  @type t :: %__MODULE__{
    :"allowedPaymentMethods" => [String.t] | nil,
    :"amount" => Adyen.Model.Amount.t,
    :"applicationInfo" => Adyen.Model.ApplicationInfo.t | nil,
    :"billingAddress" => Adyen.Model.Address1.t | nil,
    :"blockedPaymentMethods" => [String.t] | nil,
    :"countryCode" => String.t | nil,
    :"deliverAt" => DateTime.t | nil,
    :"deliveryAddress" => Adyen.Model.Address1.t | nil,
    :"description" => String.t | nil,
    :"expiresAt" => String.t | nil,
    :"id" => String.t,
    :"lineItems" => [Adyen.Model.LineItem.t] | nil,
    :"merchantAccount" => String.t,
    :"merchantOrderReference" => String.t | nil,
    :"recurringProcessingModel" => Adyen.Model.RecurringProcessingModel3.t | nil,
    :"reference" => String.t,
    :"returnUrl" => String.t | nil,
    :"reusable" => boolean() | nil,
    :"riskData" => Adyen.Model.RiskData.t | nil,
    :"shopperEmail" => String.t | nil,
    :"shopperLocale" => String.t | nil,
    :"shopperName" => Adyen.Model.Name2.t | nil,
    :"shopperReference" => String.t | nil,
    :"splits" => [Adyen.Model.Split.t] | nil,
    :"status" => Adyen.Model.Status13.t,
    :"store" => String.t | nil,
    :"storePaymentMethod" => boolean() | nil,
    :"url" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PaymentLinkResource do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"applicationInfo", :struct, Adyen.Model.ApplicationInfo, options)
    |> deserialize(:"billingAddress", :struct, Adyen.Model.Address1, options)
    |> deserialize(:"deliveryAddress", :struct, Adyen.Model.Address1, options)
    |> deserialize(:"lineItems", :list, Adyen.Model.LineItem, options)
    |> deserialize(:"recurringProcessingModel", :struct, Adyen.Model.RecurringProcessingModel3, options)
    |> deserialize(:"riskData", :struct, Adyen.Model.RiskData, options)
    |> deserialize(:"shopperName", :struct, Adyen.Model.Name2, options)
    |> deserialize(:"splits", :list, Adyen.Model.Split, options)
    |> deserialize(:"status", :struct, Adyen.Model.Status13, options)
  end
end

