# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PayoutAccountHolderRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"accountHolderCode",
    :"amount",
    :"bankAccountUUID",
    :"description",
    :"merchantReference",
    :"payoutMethodCode",
    :"payoutSpeed"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t,
    :"accountHolderCode" => String.t,
    :"amount" => Adyen.Model.Amount.t,
    :"bankAccountUUID" => String.t | nil,
    :"description" => String.t | nil,
    :"merchantReference" => String.t | nil,
    :"payoutMethodCode" => String.t | nil,
    :"payoutSpeed" => Adyen.Model.PayoutSpeed.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PayoutAccountHolderRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"payoutSpeed", :struct, Adyen.Model.PayoutSpeed, options)
  end
end

