# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PayoutSpeed do
  @moduledoc """
  Speed with which payouts for this account are processed. Permitted values: `STANDARD`, `SAME_DAY`.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PayoutSpeed do
  def decode(value, _options) do
    value
  end
end

