# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PayoutMethod do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"merchantAccount",
    :"payoutMethodCode",
    :"payoutMethodType",
    :"recurringDetailReference",
    :"shopperReference"
  ]

  @type t :: %__MODULE__{
    :"merchantAccount" => String.t,
    :"payoutMethodCode" => String.t | nil,
    :"payoutMethodType" => Adyen.Model.PayoutMethodType.t | nil,
    :"recurringDetailReference" => String.t,
    :"shopperReference" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PayoutMethod do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"payoutMethodType", :struct, Adyen.Model.PayoutMethodType, options)
  end
end

