# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PayoutScheduleResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"nextScheduledPayout",
    :"schedule"
  ]

  @type t :: %__MODULE__{
    :"nextScheduledPayout" => DateTime.t | nil,
    :"schedule" => Adyen.Model.Schedule.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PayoutScheduleResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"schedule", :struct, Adyen.Model.Schedule, options)
  end
end

