# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.PerformVerificationRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"accountStateType",
    :"tier"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"accountStateType" => AdyenForPlatforms:AccountAPI.Model.AccountStateType.t,
    :"tier" => integer()
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.PerformVerificationRequest do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accountStateType", :struct, AdyenForPlatforms:AccountAPI.Model.AccountStateType, options)
  end
end

