# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PersonalData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"dateOfBirth",
    :"idNumber",
    :"nationality"
  ]

  @type t :: %__MODULE__{
    :"dateOfBirth" => String.t | nil,
    :"idNumber" => String.t | nil,
    :"nationality" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PersonalData do
  def decode(value, _options) do
    value
  end
end

