# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PhoneNumber2 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"phoneCountryCode",
    :"phoneNumber",
    :"phoneType"
  ]

  @type t :: %__MODULE__{
    :"phoneCountryCode" => String.t,
    :"phoneNumber" => String.t,
    :"phoneType" => Adyen.Model.PhoneType.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PhoneNumber2 do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"phoneType", :struct, Adyen.Model.PhoneType, options)
  end
end

