# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Phone do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"number",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"number" => String.t,
    :"type" => Adyen.Model.Type3.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Phone do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"type", :struct, Adyen.Model.Type3, options)
  end
end

