# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.PlatformPayment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"account",
    :"description",
    :"modificationMerchantReference",
    :"modificationPspReference",
    :"paymentMerchantReference",
    :"paymentPspReference",
    :"reference",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"account" => String.t | nil,
    :"description" => String.t | nil,
    :"modificationMerchantReference" => String.t | nil,
    :"modificationPspReference" => String.t | nil,
    :"paymentMerchantReference" => String.t | nil,
    :"paymentPspReference" => String.t | nil,
    :"reference" => String.t | nil,
    :"type" => Adyen.Model.Type8.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.PlatformPayment do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"type", :struct, Adyen.Model.Type8, options)
  end
end

