# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.ReportAvailableNotificationContent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"accountType",
    :"eventDate",
    :"remoteAccessUrl",
    :"success"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t | nil,
    :"accountType" => String.t | nil,
    :"eventDate" => DateTime.t | nil,
    :"remoteAccessUrl" => String.t | nil,
    :"success" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.ReportAvailableNotificationContent do
  def decode(value, _options) do
    value
  end
end

