# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.ReportAvailableNotificationRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"live",
    :"notificationItems"
  ]

  @type t :: %__MODULE__{
    :"live" => boolean() | nil,
    :"notificationItems" => [Adyen.Model.ReportAvailableNotificationRequestItem.t] | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.ReportAvailableNotificationRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"notificationItems", :list, Adyen.Model.ReportAvailableNotificationRequestItem, options)
  end
end

