# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.ResponseAdditionalDataNetworkTokens do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"networkToken.available",
    :"networkToken.bin",
    :"networkToken.tokenSummary"
  ]

  @type t :: %__MODULE__{
    :"networkToken.available" => String.t | nil,
    :"networkToken.bin" => String.t | nil,
    :"networkToken.tokenSummary" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.ResponseAdditionalDataNetworkTokens do
  def decode(value, _options) do
    value
  end
end

