# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.Status1 do
  @moduledoc """
  The status of the account holder. >Permitted values: `Active`, `Inactive`, `Suspended`, `Closed`.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.Status1 do
  def decode(value, _options) do
    value
  end
end

