# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Status12 do
  @moduledoc """
  The status of the donation transaction.  Possible values: * **completed** * **pending** * **refused**
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Status12 do
  def decode(value, _options) do
    value
  end
end

