# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Status13 do
  @moduledoc """
  Status of the payment link. Possible values: * **active** * **expired** * **completed** (v66 and above) * **paid** (v65 and below)
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Status13 do
  def decode(value, _options) do
    value
  end
end

