# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.StoreDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"address",
    :"fullPhoneNumber",
    :"merchantAccount",
    :"merchantCategoryCode",
    :"phoneNumber",
    :"shopperInteraction",
    :"splitConfigurationUUID",
    :"status",
    :"store",
    :"storeName",
    :"storeReference",
    :"virtualAccount",
    :"webAddress"
  ]

  @type t :: %__MODULE__{
    :"address" => Adyen.Model.ViasAddress.t,
    :"fullPhoneNumber" => String.t | nil,
    :"merchantAccount" => String.t,
    :"merchantCategoryCode" => String.t,
    :"phoneNumber" => Adyen.Model.ViasPhoneNumber.t | nil,
    :"shopperInteraction" => Adyen.Model.ShopperInteraction.t | nil,
    :"splitConfigurationUUID" => String.t | nil,
    :"status" => Adyen.Model.Status.t | nil,
    :"store" => String.t | nil,
    :"storeName" => String.t | nil,
    :"storeReference" => String.t,
    :"virtualAccount" => String.t | nil,
    :"webAddress" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.StoreDetail do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address", :struct, Adyen.Model.ViasAddress, options)
    |> deserialize(:"phoneNumber", :struct, Adyen.Model.ViasPhoneNumber, options)
    |> deserialize(:"shopperInteraction", :struct, Adyen.Model.ShopperInteraction, options)
    |> deserialize(:"status", :struct, Adyen.Model.Status, options)
  end
end

