# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.StoreDetailAndSubmitRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"amount",
    :"bank",
    :"billingAddress",
    :"card",
    :"dateOfBirth",
    :"entityType",
    :"fraudOffset",
    :"merchantAccount",
    :"nationality",
    :"recurring",
    :"reference",
    :"selectedBrand",
    :"shopperEmail",
    :"shopperName",
    :"shopperReference",
    :"shopperStatement",
    :"socialSecurityNumber",
    :"telephoneNumber"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"amount" => Adyen.Model.Amount.t,
    :"bank" => Adyen.Model.BankAccount.t | nil,
    :"billingAddress" => Adyen.Model.Address1.t | nil,
    :"card" => Adyen.Model.Card2.t | nil,
    :"dateOfBirth" => DateTime.t,
    :"entityType" => Adyen.Model.EntityType5.t,
    :"fraudOffset" => integer() | nil,
    :"merchantAccount" => String.t,
    :"nationality" => String.t,
    :"recurring" => Adyen.Model.Recurring.t,
    :"reference" => String.t,
    :"selectedBrand" => String.t | nil,
    :"shopperEmail" => String.t,
    :"shopperName" => Adyen.Model.Name2.t | nil,
    :"shopperReference" => String.t,
    :"shopperStatement" => String.t | nil,
    :"socialSecurityNumber" => String.t | nil,
    :"telephoneNumber" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.StoreDetailAndSubmitRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"bank", :struct, Adyen.Model.BankAccount, options)
    |> deserialize(:"billingAddress", :struct, Adyen.Model.Address1, options)
    |> deserialize(:"card", :struct, Adyen.Model.Card2, options)
    |> deserialize(:"entityType", :struct, Adyen.Model.EntityType5, options)
    |> deserialize(:"recurring", :struct, Adyen.Model.Recurring, options)
    |> deserialize(:"shopperName", :struct, Adyen.Model.Name2, options)
  end
end

