# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.StoreDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"address",
    :"fullPhoneNumber",
    :"merchantAccount",
    :"merchantCategoryCode",
    :"phoneNumber",
    :"shopperInteraction",
    :"splitConfigurationUUID",
    :"status",
    :"store",
    :"storeName",
    :"storeReference",
    :"virtualAccount",
    :"webAddress"
  ]

  @type t :: %__MODULE__{
    :"address" => AdyenForPlatforms:AccountAPI.Model.ViasAddress7.t,
    :"fullPhoneNumber" => String.t | nil,
    :"merchantAccount" => String.t,
    :"merchantCategoryCode" => String.t,
    :"phoneNumber" => AdyenForPlatforms:AccountAPI.Model.ViasPhoneNumber3.t | nil,
    :"shopperInteraction" => AdyenForPlatforms:AccountAPI.Model.ShopperInteraction.t | nil,
    :"splitConfigurationUUID" => String.t | nil,
    :"status" => AdyenForPlatforms:AccountAPI.Model.Status.t | nil,
    :"store" => String.t | nil,
    :"storeName" => String.t | nil,
    :"storeReference" => String.t,
    :"virtualAccount" => String.t | nil,
    :"webAddress" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.StoreDetail do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"address", :struct, AdyenForPlatforms:AccountAPI.Model.ViasAddress7, options)
    |> deserialize(:"phoneNumber", :struct, AdyenForPlatforms:AccountAPI.Model.ViasPhoneNumber3, options)
    |> deserialize(:"shopperInteraction", :struct, AdyenForPlatforms:AccountAPI.Model.ShopperInteraction, options)
    |> deserialize(:"status", :struct, AdyenForPlatforms:AccountAPI.Model.Status, options)
  end
end

