# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.SubmitResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"pspReference",
    :"refusalReason",
    :"resultCode"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"pspReference" => String.t,
    :"refusalReason" => String.t | nil,
    :"resultCode" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.SubmitResponse do
  def decode(value, _options) do
    value
  end
end

