# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.SubmitRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"additionalData",
    :"amount",
    :"dateOfBirth",
    :"entityType",
    :"fraudOffset",
    :"merchantAccount",
    :"nationality",
    :"recurring",
    :"reference",
    :"selectedRecurringDetailReference",
    :"shopperEmail",
    :"shopperName",
    :"shopperReference",
    :"shopperStatement",
    :"socialSecurityNumber"
  ]

  @type t :: %__MODULE__{
    :"additionalData" => %{optional(String.t) => String.t} | nil,
    :"amount" => Adyen.Model.Amount.t,
    :"dateOfBirth" => DateTime.t | nil,
    :"entityType" => Adyen.Model.EntityType7.t | nil,
    :"fraudOffset" => integer() | nil,
    :"merchantAccount" => String.t,
    :"nationality" => String.t | nil,
    :"recurring" => Adyen.Model.Recurring.t,
    :"reference" => String.t,
    :"selectedRecurringDetailReference" => String.t,
    :"shopperEmail" => String.t,
    :"shopperName" => Adyen.Model.Name2.t | nil,
    :"shopperReference" => String.t,
    :"shopperStatement" => String.t | nil,
    :"socialSecurityNumber" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.SubmitRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"entityType", :struct, Adyen.Model.EntityType7, options)
    |> deserialize(:"recurring", :struct, Adyen.Model.Recurring, options)
    |> deserialize(:"shopperName", :struct, Adyen.Model.Name2, options)
  end
end

