# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.SweepConfiguration do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"balanceAccountId",
    :"merchantAccount",
    :"schedule",
    :"sweepAmount",
    :"targetAmount",
    :"transferInstrumentId",
    :"triggerAmount",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"balanceAccountId" => String.t | nil,
    :"merchantAccount" => String.t | nil,
    :"schedule" => Adyen.Model.SweepSchedule.t,
    :"sweepAmount" => Adyen.Model.Amount.t | nil,
    :"targetAmount" => Adyen.Model.Amount.t | nil,
    :"transferInstrumentId" => String.t | nil,
    :"triggerAmount" => Adyen.Model.Amount.t | nil,
    :"type" => Adyen.Model.Type5.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.SweepConfiguration do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"schedule", :struct, Adyen.Model.SweepSchedule, options)
    |> deserialize(:"sweepAmount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"targetAmount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"triggerAmount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type5, options)
  end
end

