# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.TestNotificationConfigurationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errorMessages",
    :"eventTypes",
    :"exchangeMessages",
    :"invalidFields",
    :"notificationId",
    :"okMessages",
    :"pspReference",
    :"resultCode"
  ]

  @type t :: %__MODULE__{
    :"errorMessages" => [String.t] | nil,
    :"eventTypes" => [Adyen.Model.EventType1.t],
    :"exchangeMessages" => [Adyen.Model.ExchangeMessage.t],
    :"invalidFields" => [Adyen.Model.ErrorFieldType.t] | nil,
    :"notificationId" => integer(),
    :"okMessages" => [String.t],
    :"pspReference" => String.t | nil,
    :"resultCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.TestNotificationConfigurationResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"eventTypes", :list, Adyen.Model.EventType1, options)
    |> deserialize(:"exchangeMessages", :list, Adyen.Model.ExchangeMessage, options)
    |> deserialize(:"invalidFields", :list, Adyen.Model.ErrorFieldType, options)
  end
end

