# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.ThreeDs2RequestData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"acquirerBIN",
    :"acquirerMerchantID",
    :"authenticationOnly",
    :"challengeIndicator",
    :"deviceChannel",
    :"deviceRenderOptions",
    :"mcc",
    :"merchantName",
    :"messageVersion",
    :"notificationURL",
    :"sdkAppID",
    :"sdkEncData",
    :"sdkEphemPubKey",
    :"sdkMaxTimeout",
    :"sdkReferenceNumber",
    :"sdkTransID",
    :"sdkVersion",
    :"threeDSCompInd",
    :"threeDSRequestorID",
    :"threeDSRequestorName",
    :"threeDSRequestorURL",
    :"transactionType",
    :"whiteListStatus"
  ]

  @type t :: %__MODULE__{
    :"acquirerBIN" => String.t | nil,
    :"acquirerMerchantID" => String.t | nil,
    :"authenticationOnly" => boolean() | nil,
    :"challengeIndicator" => Adyen.Model.ChallengeIndicator.t | nil,
    :"deviceChannel" => String.t,
    :"deviceRenderOptions" => Adyen.Model.DeviceRenderOptions.t | nil,
    :"mcc" => String.t | nil,
    :"merchantName" => String.t | nil,
    :"messageVersion" => String.t | nil,
    :"notificationURL" => String.t | nil,
    :"sdkAppID" => String.t | nil,
    :"sdkEncData" => String.t | nil,
    :"sdkEphemPubKey" => Adyen.Model.SdkEphemPubKey.t | nil,
    :"sdkMaxTimeout" => integer() | nil,
    :"sdkReferenceNumber" => String.t | nil,
    :"sdkTransID" => String.t | nil,
    :"sdkVersion" => String.t | nil,
    :"threeDSCompInd" => String.t | nil,
    :"threeDSRequestorID" => String.t | nil,
    :"threeDSRequestorName" => String.t | nil,
    :"threeDSRequestorURL" => String.t | nil,
    :"transactionType" => Adyen.Model.TransactionType.t | nil,
    :"whiteListStatus" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.ThreeDs2RequestData do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"challengeIndicator", :struct, Adyen.Model.ChallengeIndicator, options)
    |> deserialize(:"deviceRenderOptions", :struct, Adyen.Model.DeviceRenderOptions, options)
    |> deserialize(:"sdkEphemPubKey", :struct, Adyen.Model.SdkEphemPubKey, options)
    |> deserialize(:"transactionType", :struct, Adyen.Model.TransactionType, options)
  end
end

