# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.ThreeDs2CardRangeDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"brandCode",
    :"endRange",
    :"startRange",
    :"threeDS2Version",
    :"threeDSMethodURL"
  ]

  @type t :: %__MODULE__{
    :"brandCode" => String.t | nil,
    :"endRange" => String.t | nil,
    :"startRange" => String.t | nil,
    :"threeDS2Version" => String.t | nil,
    :"threeDSMethodURL" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.ThreeDs2CardRangeDetail do
  def decode(value, _options) do
    value
  end
end

