# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.TransactionEventViolation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reason",
    :"transactionRule",
    :"transactionRuleSource"
  ]

  @type t :: %__MODULE__{
    :"reason" => String.t | nil,
    :"transactionRule" => Adyen.Model.ResourceReference.t | nil,
    :"transactionRuleSource" => Adyen.Model.TransactionRuleSource.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.TransactionEventViolation do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"transactionRule", :struct, Adyen.Model.ResourceReference, options)
    |> deserialize(:"transactionRuleSource", :struct, Adyen.Model.TransactionRuleSource, options)
  end
end

