# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Transaction do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"bankAccountDetail",
    :"captureMerchantReference",
    :"capturePspReference",
    :"creationDate",
    :"description",
    :"destinationAccountCode",
    :"disputePspReference",
    :"disputeReasonCode",
    :"merchantReference",
    :"paymentPspReference",
    :"payoutPspReference",
    :"pspReference",
    :"sourceAccountCode",
    :"transactionStatus",
    :"transferCode"
  ]

  @type t :: %__MODULE__{
    :"amount" => Adyen.Model.Amount.t | nil,
    :"bankAccountDetail" => Adyen.Model.BankAccountDetail.t | nil,
    :"captureMerchantReference" => String.t | nil,
    :"capturePspReference" => String.t | nil,
    :"creationDate" => DateTime.t | nil,
    :"description" => String.t | nil,
    :"destinationAccountCode" => String.t | nil,
    :"disputePspReference" => String.t | nil,
    :"disputeReasonCode" => String.t | nil,
    :"merchantReference" => String.t | nil,
    :"paymentPspReference" => String.t | nil,
    :"payoutPspReference" => String.t | nil,
    :"pspReference" => String.t | nil,
    :"sourceAccountCode" => String.t | nil,
    :"transactionStatus" => Adyen.Model.TransactionStatus1.t | nil,
    :"transferCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Transaction do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"bankAccountDetail", :struct, Adyen.Model.BankAccountDetail, options)
    |> deserialize(:"transactionStatus", :struct, Adyen.Model.TransactionStatus1, options)
  end
end

