# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.TransferFundsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"destinationAccountCode",
    :"merchantReference",
    :"sourceAccountCode",
    :"transferCode"
  ]

  @type t :: %__MODULE__{
    :"amount" => Adyen.Model.Amount.t,
    :"destinationAccountCode" => String.t,
    :"merchantReference" => String.t | nil,
    :"sourceAccountCode" => String.t,
    :"transferCode" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.TransferFundsRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
  end
end

