# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.TransactionNotificationData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolder",
    :"amount",
    :"authCode",
    :"balanceAccount",
    :"balancePlatform",
    :"creationDate",
    :"description",
    :"id",
    :"merchantData",
    :"modification",
    :"originalAmount",
    :"paymentId",
    :"paymentInstrument",
    :"platformPayment",
    :"processingType",
    :"purposeCode",
    :"reference",
    :"relayedAuthorisationData",
    :"status",
    :"transactionRulesResult",
    :"validationResult",
    :"valueDate"
  ]

  @type t :: %__MODULE__{
    :"accountHolder" => Adyen.Model.ResourceReference.t | nil,
    :"amount" => Adyen.Model.Amount.t | nil,
    :"authCode" => String.t | nil,
    :"balanceAccount" => Adyen.Model.ResourceReference.t | nil,
    :"balancePlatform" => String.t,
    :"creationDate" => DateTime.t,
    :"description" => String.t | nil,
    :"id" => String.t,
    :"merchantData" => Adyen.Model.MerchantData.t | nil,
    :"modification" => Adyen.Model.NotificationModificationData.t | nil,
    :"originalAmount" => Adyen.Model.Amount.t | nil,
    :"paymentId" => String.t | nil,
    :"paymentInstrument" => Adyen.Model.ResourceReference.t | nil,
    :"platformPayment" => Adyen.Model.PlatformPayment.t | nil,
    :"processingType" => String.t | nil,
    :"purposeCode" => String.t | nil,
    :"reference" => String.t | nil,
    :"relayedAuthorisationData" => Adyen.Model.RelayedAuthorisationData.t | nil,
    :"status" => String.t | nil,
    :"transactionRulesResult" => Adyen.Model.TransactionRulesResult.t | nil,
    :"validationResult" => [Adyen.Model.ValidationResult.t] | nil,
    :"valueDate" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.TransactionNotificationData do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accountHolder", :struct, Adyen.Model.ResourceReference, options)
    |> deserialize(:"amount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"balanceAccount", :struct, Adyen.Model.ResourceReference, options)
    |> deserialize(:"merchantData", :struct, Adyen.Model.MerchantData, options)
    |> deserialize(:"modification", :struct, Adyen.Model.NotificationModificationData, options)
    |> deserialize(:"originalAmount", :struct, Adyen.Model.Amount, options)
    |> deserialize(:"paymentInstrument", :struct, Adyen.Model.ResourceReference, options)
    |> deserialize(:"platformPayment", :struct, Adyen.Model.PlatformPayment, options)
    |> deserialize(:"relayedAuthorisationData", :struct, Adyen.Model.RelayedAuthorisationData, options)
    |> deserialize(:"transactionRulesResult", :struct, Adyen.Model.TransactionRulesResult, options)
    |> deserialize(:"validationResult", :list, Adyen.Model.ValidationResult, options)
  end
end

