# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Type22 do
  @moduledoc """
  The type of conditions provided in the rule.  Possible values:   * **allowList** - The rule provides categories (such as country and MCC) where payments must be allowed.  * **blockList** - The rule provides categories (such as country and MCC) where payments must be blocked.  * **maxUsage** - The rule sets limits for the maximum amount or maximum number of transactions for the lifetime of the payment instrument.  * **velocity** - The rule sets limits for the maximum amount or maximum number of transactions for a given time interval.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Type22 do
  def decode(value, _options) do
    value
  end
end

