# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Type4 do
  @moduledoc """
  The schedule type.  Possible values:  * **daily**: Push out funds daily at 07:00 AM CET.  * **weekly**: Push out funds every Monday at 07:00 AM CET.  * **monthly**: Push out funds every 1st of the month at 07:00 AM CET.  * **balance**: Only for sweeps of `type` **pull** and with a `merchantAccount` source. Pull in funds instantly if the balance is less than or equal to the `triggerAmount`.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Type4 do
  def decode(value, _options) do
    value
  end
end

