# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.UltimateParentCompanyBusinessDetails2 do
  @moduledoc """
  Details about the ultimate parent company's business.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"legalBusinessName",
    :"registrationNumber",
    :"stockExchange",
    :"stockNumber",
    :"stockTicker"
  ]

  @type t :: %__MODULE__{
    :"legalBusinessName" => String.t | nil,
    :"registrationNumber" => String.t | nil,
    :"stockExchange" => String.t | nil,
    :"stockNumber" => String.t | nil,
    :"stockTicker" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.UltimateParentCompanyBusinessDetails2 do
  def decode(value, _options) do
    value
  end
end

