# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.UpdateAccountResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountCode",
    :"bankAccountUUID",
    :"description",
    :"invalidFields",
    :"metadata",
    :"payoutMethodCode",
    :"payoutSchedule",
    :"payoutSpeed",
    :"pspReference",
    :"resultCode"
  ]

  @type t :: %__MODULE__{
    :"accountCode" => String.t,
    :"bankAccountUUID" => String.t | nil,
    :"description" => String.t | nil,
    :"invalidFields" => [Adyen.Model.ErrorFieldType.t] | nil,
    :"metadata" => %{optional(String.t) => String.t} | nil,
    :"payoutMethodCode" => String.t | nil,
    :"payoutSchedule" => Adyen.Model.PayoutScheduleResponse.t | nil,
    :"payoutSpeed" => Adyen.Model.PayoutSpeed.t | nil,
    :"pspReference" => String.t | nil,
    :"resultCode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.UpdateAccountResponse do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"invalidFields", :list, Adyen.Model.ErrorFieldType, options)
    |> deserialize(:"payoutSchedule", :struct, Adyen.Model.PayoutScheduleResponse, options)
    |> deserialize(:"payoutSpeed", :struct, Adyen.Model.PayoutSpeed, options)
  end
end

