# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.UpdateAccountHolderRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"accountHolderDetails",
    :"description",
    :"legalEntity",
    :"primaryCurrency",
    :"processingTier",
    :"verificationProfile"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"accountHolderDetails" => AdyenForPlatforms:AccountAPI.Model.AccountHolderDetails4.t | nil,
    :"description" => String.t | nil,
    :"legalEntity" => AdyenForPlatforms:AccountAPI.Model.LegalEntity.t | nil,
    :"primaryCurrency" => String.t | nil,
    :"processingTier" => integer() | nil,
    :"verificationProfile" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.UpdateAccountHolderRequest do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accountHolderDetails", :struct, AdyenForPlatforms:AccountAPI.Model.AccountHolderDetails4, options)
    |> deserialize(:"legalEntity", :struct, AdyenForPlatforms:AccountAPI.Model.LegalEntity, options)
  end
end

