# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.UpdateAccountHolderStateRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountHolderCode",
    :"disable",
    :"reason",
    :"stateType"
  ]

  @type t :: %__MODULE__{
    :"accountHolderCode" => String.t,
    :"disable" => boolean(),
    :"reason" => String.t | nil,
    :"stateType" => Adyen.Model.StateType.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.UpdateAccountHolderStateRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"stateType", :struct, Adyen.Model.StateType, options)
  end
end

