# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.UpdateNotificationConfigurationRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"configurationDetails"
  ]

  @type t :: %__MODULE__{
    :"configurationDetails" => Adyen.Model.NotificationConfigurationDetails.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.UpdateNotificationConfigurationRequest do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"configurationDetails", :struct, Adyen.Model.NotificationConfigurationDetails, options)
  end
end

