# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Upi do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"billingSequenceNumber",
    :"recurringDetailReference",
    :"shopperNotificationReference",
    :"storedPaymentMethodId",
    :"type",
    :"virtualPaymentAddress"
  ]

  @type t :: %__MODULE__{
    :"billingSequenceNumber" => String.t,
    :"recurringDetailReference" => String.t | nil,
    :"shopperNotificationReference" => String.t | nil,
    :"storedPaymentMethodId" => String.t | nil,
    :"type" => String.t,
    :"virtualPaymentAddress" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Upi do
  def decode(value, _options) do
    value
  end
end

