# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.UploadDocumentRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"documentContent",
    :"documentDetail"
  ]

  @type t :: %__MODULE__{
    :"documentContent" => String.t,
    :"documentDetail" => AdyenForPlatforms:AccountAPI.Model.DocumentDetail1.t
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.UploadDocumentRequest do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"documentDetail", :struct, AdyenForPlatforms:AccountAPI.Model.DocumentDetail1, options)
  end
end

