# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.ViasName do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"firstName",
    :"gender",
    :"infix",
    :"lastName"
  ]

  @type t :: %__MODULE__{
    :"firstName" => String.t,
    :"gender" => Adyen.Model.Gender.t | nil,
    :"infix" => String.t | nil,
    :"lastName" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.ViasName do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"gender", :struct, Adyen.Model.Gender, options)
  end
end

