# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.ViasPersonalData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"dateOfBirth",
    :"documentData",
    :"nationality"
  ]

  @type t :: %__MODULE__{
    :"dateOfBirth" => String.t | nil,
    :"documentData" => [AdyenForPlatforms:AccountAPI.Model.PersonalDocumentData.t] | nil,
    :"nationality" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.ViasPersonalData do
  import AdyenForPlatforms:AccountAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"documentData", :list, AdyenForPlatforms:AccountAPI.Model.PersonalDocumentData, options)
  end
end

