# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule AdyenForPlatforms:AccountAPI.Model.ViasAddress1 do
  @moduledoc """
  Address of the ultimate parent company.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"city",
    :"country",
    :"houseNumberOrName",
    :"postalCode",
    :"stateOrProvince",
    :"street"
  ]

  @type t :: %__MODULE__{
    :"city" => String.t | nil,
    :"country" => String.t,
    :"houseNumberOrName" => String.t | nil,
    :"postalCode" => String.t | nil,
    :"stateOrProvince" => String.t | nil,
    :"street" => String.t | nil
  }
end

defimpl Poison.Decoder, for: AdyenForPlatforms:AccountAPI.Model.ViasAddress1 do
  def decode(value, _options) do
    value
  end
end

