# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.Vipps do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"recurringDetailReference",
    :"storedPaymentMethodId",
    :"telephoneNumber",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"recurringDetailReference" => String.t | nil,
    :"storedPaymentMethodId" => String.t | nil,
    :"telephoneNumber" => String.t,
    :"type" => Adyen.Model.Type55.t | nil
  }
end

defimpl Poison.Decoder, for: Adyen.Model.Vipps do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"type", :struct, Adyen.Model.Type55, options)
  end
end

