# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Model.VisaCheckout do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"fundingSource",
    :"type",
    :"visaCheckoutCallId"
  ]

  @type t :: %__MODULE__{
    :"fundingSource" => Adyen.Model.FundingSource.t | nil,
    :"type" => Adyen.Model.Type56.t | nil,
    :"visaCheckoutCallId" => String.t
  }
end

defimpl Poison.Decoder, for: Adyen.Model.VisaCheckout do
  import Adyen.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"fundingSource", :struct, Adyen.Model.FundingSource, options)
    |> deserialize(:"type", :struct, Adyen.Model.Type56, options)
  end
end

