# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Api.HostedOnboardingPage do
  @moduledoc """
  API calls for all endpoints tagged `HostedOnboardingPage`.
  """

  alias Adyen.Connection
  import Adyen.RequestBuilder


  @doc """
  post-getOnboardingUrl
  Returns a link to an Adyen-hosted onboarding page (HOP) that you can send to your account holder. For more information on how to use HOP, refer to [Hosted onboarding](https://docs.adyen.com/platforms/hosted-onboarding-page).

  ## Parameters

  - connection (Adyen.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :body (GetOnboardingUrlRequest): 
  ## Returns

  {:ok, Adyen.Model.GetOnboardingUrlResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec post_get_onboarding_url(Tesla.Env.client, keyword()) :: {:ok, Adyen.Model.GetOnboardingUrlResponse.t} | {:ok, Adyen.Model.ServiceError.t} | {:error, Tesla.Env.t}
  def post_get_onboarding_url(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/getOnboardingUrl")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %Adyen.Model.GetOnboardingUrlResponse{}},
      { 400, %Adyen.Model.ServiceError{}},
      { 401, %Adyen.Model.ServiceError{}},
      { 403, %Adyen.Model.ServiceError{}},
      { 422, %Adyen.Model.ServiceError{}},
      { 500, %Adyen.Model.ServiceError{}}
    ])
  end
end
