# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Adyen.Api.PCIComplianceQuestionnairePage do
  @moduledoc """
  API calls for all endpoints tagged `PCIComplianceQuestionnairePage`.
  """

  alias Adyen.Connection
  import Adyen.RequestBuilder


  @doc """
  post-getPciQuestionnaireUrl
  Returns a link to a PCI compliance questionnaire that you can send to your account holder.  > You should only use this endpoint if you have a [partner platform setup](https://docs.adyen.com/platforms/platforms-for-partners).

  ## Parameters

  - connection (Adyen.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :body (GetPciUrlRequest): 
  ## Returns

  {:ok, Adyen.Model.GetPciUrlResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec post_get_pci_questionnaire_url(Tesla.Env.client, keyword()) :: {:ok, Adyen.Model.GetPciUrlResponse.t} | {:ok, Adyen.Model.ServiceError.t} | {:error, Tesla.Env.t}
  def post_get_pci_questionnaire_url(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/getPciQuestionnaireUrl")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %Adyen.Model.GetPciUrlResponse{}},
      { 400, %Adyen.Model.ServiceError{}},
      { 401, %Adyen.Model.ServiceError{}},
      { 403, %Adyen.Model.ServiceError{}},
      { 422, %Adyen.Model.ServiceError{}},
      { 500, %Adyen.Model.ServiceError{}}
    ])
  end
end
